In [1]:
import json
import time
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import *
from sklearn.base import clone

## 進行 V1 / V2 總整理

In [2]:
VERSION_INFO = {"V1": {"sample_points": 100,
                       "raw_features": 100,
                       "feature_count": 106},
                "V2": {"sample_points": 10,
                       "raw_features": 10,
                       "feature_count": 16}}
LABEL_NAMES = {"linear": "Linear",
               "quadratic": "Quadratic",
               "cubic": "Cubic",
               "exponential": "Exponential",
               "logarithmic": "Logarithmic",
               "sine": "Sine",
               "cosine": "Cosine",
               "reciprocal": "Reciprocal"}
LABEL_ORDER = list(LABEL_NAMES.keys())

### 載入 V1 結合後的資料

In [3]:
data1 = pd.read_csv(r'D:\Python\我的AI作品集\專案1_數學函數辨識\data\v1\function_dataset_merged.csv')

In [4]:
X1 = data1.drop(['label'], axis=1)
y1 = data1['label']

In [5]:
train_v1_rows = int(len(data1)*0.8)
X1_train = X1.iloc[:train_v1_rows].copy()
X1_test = X1.iloc[train_v1_rows:].copy()
y1_train = y1.iloc[:train_v1_rows].copy()
y1_test = y1.iloc[train_v1_rows:].copy()

In [6]:
# 載入 V1 最終模型
model_v1_package = joblib.load(r'D:\Python\我的AI作品集\專案1_數學函數辨識\models\v1\final_model.joblib')

In [7]:
v1_final_model = model_v1_package['model']
v1_feature_names = model_v1_package['feature_names']

In [8]:
train_v1_pred = v1_final_model.predict(X1_train)
train_v1_acc = accuracy_score(y1_train, train_v1_pred)
test_v1_pred = v1_final_model.predict(X1_test)
test_v1_acc = accuracy_score(y1_test, test_v1_pred)
v1_error = len(y1_test) - int(np.sum(test_v1_pred == y1_test))

In [9]:
# 測量重新訓練時間
v1_model_for_timing = clone(v1_final_model)

start_time = time.perf_counter()
v1_model_for_timing.fit(X1_train, y1_train)
v1_training_time = time.perf_counter() - start_time

In [10]:
print("----V1 / V2模型總整理----")
print("V1模型:")
print(f"訓練數據準確度: {train_v1_acc:.4f}")
print(f"測試數據準確度: {test_v1_acc:.4f}")
print(f"訓練時間: {v1_training_time:.4f} 秒")
print(f"錯誤率: {v1_error / len(y1_test):.4f}")

----V1 / V2模型總整理----
V1模型:
訓練數據準確度: 1.0000
測試數據準確度: 0.8163
訓練時間: 1.4914 秒
錯誤率: 0.1837


In [11]:
print(f"混淆矩陣:\n{confusion_matrix(y1_test, test_v1_pred, labels=LABEL_ORDER)}\n")

混淆矩陣:
[[72  1  1  9  4  1  0 12]
 [ 8 73  4  2  9  1  1  2]
 [ 2 11 85  0  1  1  0  0]
 [ 1  2  1 86  0  0  0 10]
 [ 5  1  0  9 69  1  4 11]
 [ 0  0  0  1  1 93  4  1]
 [ 0  2  0  0  1  1 95  1]
 [ 3  2  1  9  5  0  0 80]]



In [12]:
print(f"分類報告:\n{classification_report(y1_test, test_v1_pred, labels=LABEL_ORDER,
                                      target_names=[LABEL_NAMES[x] for x in LABEL_ORDER])}\n\n")

分類報告:
              precision    recall  f1-score   support

      Linear       0.79      0.72      0.75       100
   Quadratic       0.79      0.73      0.76       100
       Cubic       0.92      0.85      0.89       100
 Exponential       0.74      0.86      0.80       100
 Logarithmic       0.77      0.69      0.73       100
        Sine       0.95      0.93      0.94       100
      Cosine       0.91      0.95      0.93       100
  Reciprocal       0.68      0.80      0.74       100

    accuracy                           0.82       800
   macro avg       0.82      0.82      0.82       800
weighted avg       0.82      0.82      0.82       800





### 載入 V2 結合後的資料

In [13]:
data2 = pd.read_csv(r'D:\Python\我的AI作品集\專案1_數學函數辨識\data\v2\function_dataset_merged_v2.csv')

In [14]:
X2 = data2.drop(['label'], axis=1)
y2 = data2['label']

In [15]:
train_v2_rows = int(len(data2)*0.8)
X2_train = X2.iloc[:train_v2_rows].copy()
X2_test = X2.iloc[train_v2_rows:].copy()
y2_train = y2.iloc[:train_v2_rows].copy()
y2_test = y2.iloc[train_v2_rows:].copy()

In [16]:
# 載入 V2 最終模型
model_v2_package = joblib.load(r'D:\Python\我的AI作品集\專案1_數學函數辨識\models\v2\final_model_v2.joblib')

In [17]:
v2_final_model = model_v2_package['model']
v2_feature_names = model_v2_package['feature_names']

In [18]:
train_v2_pred = v2_final_model.predict(X2_train)
train_v2_acc = accuracy_score(y2_train, train_v2_pred)
test_v2_pred = v2_final_model.predict(X2_test)
test_v2_acc = accuracy_score(y2_test, test_v2_pred)
v2_error = len(y2_test) - int(np.sum(test_v2_pred == y2_test))

In [19]:
# 測量重新訓練時間
v2_model_for_timing = clone(v2_final_model)

start_time = time.perf_counter()
v2_model_for_timing.fit(X2_train, y2_train)
v2_training_time = time.perf_counter() - start_time

In [20]:
print("V2模型:")
print(f"訓練數據準確度: {train_v2_acc:.4f}")
print(f"測試數據準確度: {test_v2_acc:.4f}")
print(f"訓練時間: {v2_training_time:.4f} 秒")
print(f"錯誤率: {v2_error / len(y2_test):.4f}")

V2模型:
訓練數據準確度: 1.0000
測試數據準確度: 0.8250
訓練時間: 0.7489 秒
錯誤率: 0.1750


In [21]:
print(f"混淆矩陣:\n{confusion_matrix(y2_test, test_v2_pred, labels=LABEL_ORDER)}\n")

混淆矩陣:
[[85  2  0  7  6  0  0  0]
 [ 6 84  6  3  0  0  1  0]
 [ 0 16 76  5  0  3  0  0]
 [13 17  5 54  6  0  1  4]
 [ 3  0  0  1 94  0  0  2]
 [ 0  0  0  0  0 88  9  3]
 [ 0  0  0  1  1 12 85  1]
 [ 0  0  0  5  1  0  0 94]]



In [22]:
print(f"分類報告:\n{classification_report(y2_test, test_v2_pred, labels=LABEL_ORDER,
                                      target_names=[LABEL_NAMES[x] for x in LABEL_ORDER])}\n")

分類報告:
              precision    recall  f1-score   support

      Linear       0.79      0.85      0.82       100
   Quadratic       0.71      0.84      0.77       100
       Cubic       0.87      0.76      0.81       100
 Exponential       0.71      0.54      0.61       100
 Logarithmic       0.87      0.94      0.90       100
        Sine       0.85      0.88      0.87       100
      Cosine       0.89      0.85      0.87       100
  Reciprocal       0.90      0.94      0.92       100

    accuracy                           0.82       800
   macro avg       0.82      0.82      0.82       800
weighted avg       0.82      0.82      0.82       800




### 選出最佳模型

In [23]:
higher_model = f"V1 {v1_final_model}" if (test_v1_acc >= test_v2_acc) else f"V2 {v2_final_model}"
print(f"最佳模型: {higher_model}\n")

最佳模型: V2 RandomForestClassifier(random_state=10)



## 將整理結果做成表格

In [24]:
comparison_df = pd.DataFrame([{"version": "V1",
                               "model": type(v1_final_model).__name__,
                               "sample_points": VERSION_INFO["V1"]["sample_points"],
                               "raw_features": VERSION_INFO["V1"]["raw_features"],
                               "feature_count": VERSION_INFO["V1"]["feature_count"],
                               "train_accuracy": train_v1_acc,
                               "test_accuracy": test_v1_acc,
                               "error_rate": v1_error / len(y1_test),
                               "training_time_seconds": v1_training_time},
                              {"version": "V2",
                               "model": type(v2_final_model).__name__,
                               "sample_points": VERSION_INFO["V2"]["sample_points"],
                               "raw_features": VERSION_INFO["V2"]["raw_features"],
                               "feature_count": VERSION_INFO["V2"]["feature_count"],
                               "train_accuracy": train_v2_acc,
                               "test_accuracy": test_v2_acc,
                               "error_rate": v2_error / len(y2_test),
                               "training_time_seconds": v2_training_time}])

In [25]:
comparison_df.to_csv(
    r'D:\Python\我的AI作品集\專案1_數學函數辨識\data\comparison_results\v1_v2_final_comparison.csv',
    index=False)

In [26]:
comparison_df.to_html(r'D:\Python\我的AI作品集\專案1_數學函數辨識\data\comparison_results\v1_v2_final_comparison.html')

In [27]:
accuracy_difference = test_v1_acc - test_v2_acc

In [28]:
comparison_json = {"V1": {"model": type(v1_final_model).__name__,
                          "sample_points": VERSION_INFO["V1"]["sample_points"],
                          "raw_features": VERSION_INFO["V1"]["raw_features"],
                          "feature_count": VERSION_INFO["V1"]["feature_count"],
                          "train_accuracy": train_v1_acc,
                          "test_accuracy": test_v1_acc,
                          "error_rate": v1_error / len(y1_test),
                          "training_time_seconds": v1_training_time,
                          "confusion_matrix": confusion_matrix(y1_test,
                                                               test_v1_pred,
                                                               labels=LABEL_ORDER).tolist()},
                   "V2": {"model": type(v2_final_model).__name__,
                          "sample_points": VERSION_INFO["V2"]["sample_points"],
                          "raw_features": VERSION_INFO["V2"]["raw_features"],
                          "feature_count": VERSION_INFO["V2"]["feature_count"],
                          "train_accuracy": train_v2_acc,
                          "test_accuracy": test_v2_acc,
                          "error_rate": v2_error / len(y2_test),
                          "training_time_seconds": v2_training_time,
                          "confusion_matrix": confusion_matrix(y2_test,
                                                               test_v2_pred,
                                                               labels=LABEL_ORDER).tolist()},
                   "comparison": {"accuracy_difference_v1_minus_v2": accuracy_difference,
                                  "higher_test_accuracy_version": higher_model}
                  }

In [29]:
with open(r'D:\Python\我的AI作品集\專案1_數學函數辨識\data\comparison_results\v1_v2_final_comparison.json', 'w', encoding='utf-8') as f:
    json.dump(comparison_json, f, ensure_ascii=False, indent=4)

In [30]:
print("最終比較結果已儲存!")

最終比較結果已儲存!
